basket/urls.py
from re import template
from django.urls import path
from basket import views

app_name = 'basket'

urlpatterns = [
    path('', views.BasketSummary.as_view(), name='basket_summary'), 
    path('add/', views.BasketAddView.as_view(), name='basket_add'),
]
 

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jewelry_store.urls', namespace='jewelry_store')),
    path('basket/', include('basket.urls', namespace='basket')), 
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

jewelry_store/urls.py
from unicodedata import name

from django.urls import path

from jewelry_store.models import Category

from . import views

app_name = 'jewelry_store'

urlpatterns = [
    path('', views.AllListView.as_view(), name='all_products'),
    path('<slug:slug>', views.ProductView.as_view(), name='product_detail'),
    path('category/<slug:slug>/', views.CategoryView.as_view(), name='all_categories'),
    path('collection/<slug:slug>/', views.CollectionView.as_view(), name='all_collections'),
    
]
 

jewelry_store/models.py
from __future__ import annotations

import collections
from ast import arg, mod
from asyncio.windows_events import NULL
from decimal import Decimal
from email.policy import default
from itertools import product
from pickle import EMPTY_DICT, TRUE
from queue import Empty
from random import choice, choices
from tabnanny import verbose
from traceback import print_exception
from unicodedata import category, name

import pkg_resources
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Avg, Sum
from django.forms import DecimalField
from django.urls import reverse
from multiselectfield import MultiSelectField

Au = "gold"
Ag = "silver"
AuWoo = "wood&gold"
AgWoo = "wood&silver"
MATERIAL_CHOICES = [
    (Au, "gold"),
    (Ag,"silver"),
    (AuWoo, "wood&gold"),
    (AgWoo, "wood&silver"),
]

_999 = ".999"
_925 = ".925"
_875 = ".875"
_830 = ".830"
_800 = ".800"
_960 = ".960"
_750 = ".750"
_585 = ".585"
_500 = ".500"
_375 = ".375"
_333 = ".333"
PURITY_CHOICES =[
    (_999, ".999"),(_925, ".925"),(_875, ".875"),(_830, ".830"),
    (_800, ".800"),(_960, ".960"),(_750, ".750"),(_585, ".585"),
    (_500, ".500"),(_375, ".375"),(_333, ".333"),
]
_5  = "5/ø14mm/US4"
_6  = "6/ø14.3mm/US4+"
_7  = "7/ø14.6mm/"
_8  = "8/ø15mm/US5"
_9  = "9/ø15.3mm"
_10 = "10/ø15.6mm/US6-"
_11 = "11/ø16mm/US6"
_12 = "12/ø16.3mm"
_13 = "13/ø16.6mm"
_14 = "14/ø17mm/US7"
_15 = "15/ø17.3mm"
_16 = "16/ø17.6mm/US7+"
_17 = "17/ø18mm/US8"
_18 = "18/ø18.3mm"
_19 = "19/ø18.6mm/US9"
_20 = "20/ø19mm"
_21 = "21/ø19.3mm/US9+"
_22 = "22/ø19.6mm/US10"
_23 = "23/ø20mm"
_24 = "24/ø20.3mm/US11-"
_25 = "25/ø20.6mm/US11"
_26 = "26/ø21mm"
_27 = "27/ø21.3/US12"
_28 = "28/ø21.6"
_29 = "29/ø22mm/US13-"
_30 = "30/ø22.3mm/US13"
_31 = "31/ø22.6mm"
_32 = "32/ø23mm/US14"
_33 = "33/ø23.3mm"
_34 = "34/ø23.6mm"
SIZE_CHOICES  =  [
    (_5 , "5/ø14mm/US4"), (_6 , "6/ø14.3mm/US4+"), (_7 , "7/ø14.6mm/"),
    (_8 , "8/ø15mm/US5"),(_9 , "9/ø15.3mm"), (_10, "10/ø15.6mm/US6-"),
    (_11, "11/ø16mm/US6"), (_12, "12/ø16.3mm"), (_13, "13/ø16.6mm"),
    (_14, "14/ø17mm/US7"), (_15, "15/ø17.3mm"), (_16, "16/ø17.6mm/US7+"),
    (_17, "17/ø18mm/US8"), (_18, "18/ø18.3mm"), (_19, "19/ø18.6mm/US9"),
    (_20, "20/ø19mm"), (_21, "21/ø19.3mm/US9+"), (_22, "22/ø19.6mm/US10"),
    (_23, "23/ø20mm"), (_24, "24/ø20.3mm/US11-"), (_25, "25/ø20.6mm/US11"),
    (_26, "26/ø21mm"), (_27, "27/ø21.3/US12"), (_28, "28/ø21.6"),
    (_29, "29/ø22mm/US13-"), (_30, "30/ø22.3mm/US13"), (_31, "31/ø22.6mm"),
    (_32, "32/ø23mm/US14"), (_33, "33/ø23.3mm"), (_34, "34/ø23.6mm"),
 ]
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True,in_stock=True)

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse("jewelry_store:all_categories", args=[self.slug])
    
    def __str__(self):
        return self.name


class Collection(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)

    class Meta:
        verbose_name_plural = 'Collections'
    
    def get_absolute_url(self):
        return reverse("jewelry_store:all_collections", args=[self.slug])

    def __str__(self):
        return self.name

    @property
    def price(self):
        price = 0
        for product in self.products.all():
            price += product.price
        return price    


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    colection_name = models.ForeignKey(Collection, related_name='products', on_delete=models.CASCADE, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)   
    name = models.CharField(max_length=255)
    model_number = models.CharField(max_length=50)
    material = models.CharField(max_length=50, choices=MATERIAL_CHOICES, default="silver")
    purity = models.CharField(max_length=4, choices=PURITY_CHOICES,default=".925")
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    dimension = models.CharField(max_length=255)  ###!!!
    image = models.ImageField(upload_to = 'images/', default='images/default.jpg') ###!!! only one option
    price = models.DecimalField(max_digits=6, decimal_places=2)
    promo_price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    slug = models.SlugField(max_length=255)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    not_new = models.BooleanField(default=True)
    size = MultiSelectField(choices=SIZE_CHOICES,blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    products = ProductManager()

    @property
    def quantity(self):
        quantity = 0
        if not self.size:
            quantity = 1
        else:
            store = len(self.size)
            quantity += store
        return quantity



    class Meta():
        verbose_name_plural = 'Products'
        ordering = ('-created','-updated','weight', 'price',) 

    def get_absolute_url(self):
        return reverse("jewelry_store:product_detail", args=[self.slug])
    #def collection_sumarum(self):#    v=Product.objects.filter(price=True).aggregate(Sum('price'))#    print(v)# collections=Product.objects.get(pk=colection_name_id).aggregate(Sum('price'))# key_collections = Collection.id.#collections = Product.objects.filter(colection_name_id=1)#print('COLLECTIONS',collections)# for product in collections:#     Decimal(product.price)#     price = []#     a=type(Decimal(product.price))#     # print(a)#     # print(price)#     price.append(Decimal(product.price))# print(price)# print('FIRST',product.price)# print("ŁołołO",price)# v=Product.objects.aggregate(Sum('price')){{ p.collection_sumarum }}# print(collections)# return print('COLLECTIONS',collections)

    # def sum_total(self) :
    #     queryset = Product.objects.filter(in_stock=True)
    #     collections = Collection.objects.all()
    #     sum_tot=0
    #     for col in collections:
    #         for qs in queryset:
    #             if qs.colection_name_id == col.id:
    #                 sum_tot += qs.price
    #                 print('sum_tot',sum_tot)
    #     # queryset = sum_tot
    #     # print("bbbbbb",queryset)    
    #     return sum_tot

    def sum_total(self) :
        queryset = Product.objects.filter(in_stock=True)
        collections = Collection.objects.all()
        sum_tot=0
        for col in collections:
            for qs in queryset:
                if qs.colection_name_id == col.id:
                    sum_tot += qs.price
                    print('sum_tot',sum_tot)
        # queryset = sum_tot
        # print("bbbbbb",queryset)    
    def sum_total(self) :
        queryset = Product.products.filter(in_stock=True)
        collections = Collection.objects.all()
        sum_tot=0
        sum_tot_list = []
        num = len(collections)
        print('numer dlugosci listy',num)
        for col in collections:
            print(col.id)
            print(collections)    
                
            
            for qs in queryset:
                # for col.id in collections:
                    # print("col.id", col.id)
                if col.id ==  qs.colection_name_id:
                   
                    sum_tot += qs.price
                    
                    
                    print('sum_tot',sum_tot)
                    sum_tot_list.append(sum_tot)
        # queryset = sum_tot
        # print("bbbbbb",queryset)    
            return sum_tot

    def __str__(self):
        return self.name


# python manage.py makemigrations and python manage.py migrate

        

jewelry_store/views.py
import collections
from gettext import Catalog
from multiprocessing import context

from django.db.models import Sum
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.views.generic import DetailView, ListView
from pyexpat import model

import jewelry_store

from .models import Category, Collection, Product


class AllListView(ListView):
    context_object_name = 'all_products'
    queryset = Product.products.filter(in_stock=True, is_active = True)
    template_name = 'jewelry_store/home.html'
    # pk_url_kwarg='collection_id' 
    
    def get_context_data(self, **kwargs,):
        
        context = super(AllListView,self).get_context_data(**kwargs)
           
        print('dupaaaa',kwargs)
        # print(context)
        context['collections'] =  Collection.objects.all
        context['products'] = self.queryset
        
        context['sum']= Product.products.all()
        
        print("DUPA1",Product.products.filter(colection_name=1))
        print("DUPA2",Product.products.filter(colection_name=self.kwargs.get('collection_id')))
        context['prodo'] = Product.products.all().aggregate(Sum('price'))['price__sum']
        print("context['prodo']",context['prodo'])

        return context
        
    def get_queryset(self) :
        queryset = Product.products.filter(in_stock=True, is_active=True)
        collections = Collection.objects.all()
        sum_tot=0
        for col in collections:
            for qs in queryset:
                if qs.colection_name_id == col.id:
                    sum_tot += qs.price
                    print('sum_tot',sum_tot)
        queryset = sum_tot
        print("aaaaaa",queryset)    
        return queryset


class ProductView(DetailView):
    context_object_name = 'product_detail'
    model = Product
    template_name = "jewelry_store/product/detail_product.html"

    # it shows 404 when object is not in stock 
    def get_object(self):
        obj = super().get_object()
        obj = get_object_or_404(Product, slug=self.kwargs['slug'] ,in_stock=True)
        return obj
class CategoryView(ListView):
    model = Category
    context_object_name = 'all_categories'
    template_name = 'jewelry_store/product/category.html'

    def get_queryset(self):
        products = Product.products.filter(category__slug=self.kwargs['slug'],in_stock=True, is_active=True)
        # the same but shorter, was down # category = get_object_or_404(Category,slug=self.kwargs['slug'])# print(category)# products = Product.objects.filter(category=category)# print(products)
        return products    #Product.objects.filter(category=category)#products#Product.objects.filter(category=category)#products#
    
    def get_context_data(self,**kwargs):
        context = super(CategoryView,self).get_context_data(**kwargs)
        context['category'] = get_object_or_404(Category,slug=self.kwargs['slug'])
        return context
class CollectionView(ListView):
    #  context_object_name = 'collection_detail'#  queryset = Product.objects.all#  template_name = "jewelry_store/product/detail_collection.html"#  def get_context_data(self,**kwargs):#     context = super(ListView,self).get_context_data(**kwargs)#     context['collections'] =  Collection.objects.all #     context['products'] = self.queryset#     return context
    model = Collection
    context_object_name = 'all_collections'
    template_name = 'jewelry_store/product/collections.html'
    pk_url_kwarg = 'collection_id'
    
    def get_queryset(self):
        products = Product.products.filter(colection_name__slug=self.kwargs['slug'],in_stock=True, is_active=True)
        # the same but shorter, was down # category = get_object_or_404(Category,slug=self.kwargs['slug'])# print(category)# products = Product.objects.filter(category=category)# print(products)
        return products    #Product.objects.filter(category=category)#products#Product.objects.filter(category=category)#products#
    
    def get_context_data(self,**kwargs):
        context = super(CollectionView,self).get_context_data(**kwargs)
        context['collection'] = get_object_or_404(Collection,slug=self.kwargs['slug'])
        products = Product.products.filter(colection_name__slug=self.kwargs['slug'])
        context['prodo'] = products.aggregate(Sum('price'))
        return context

templates/jewelry_store/base.html
{%load static %}
{%  load menu_data_products %}
{% load menu_data_categories %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}JewelrySite{% endblock  %}</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous">
  </script>
</head>

<body>

  <header class="p-3 bg-dark text-white">
    <div class="container-fluid">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
            <use xlink:href="#bootstrap"></use>
          </svg>
        </a>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="/">Jewelry Store </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">


                <ul class="navbar-nav">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="pierwsz dupa" id="navbarDarkDropdownMenuLink"
                      role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Products
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                      <li>
                        {% menu_data_products as menu %}

                        {% comment %} categories are name from templatetag, named by me as key {% endcomment %}
                        {% for cat in menu.categories %}
                        <a class="dropdown-item" href="{{cat.get_absolute_url}}">{{cat.name|title}} </a>
                        {% endfor %}
                      </li>
                    </ul>
                  </li>
                </ul>


                <ul class="navbar-nav">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="druga dupa dupa" id="navbarDarkDropdownMenuLink"
                      role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Collections
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                      <li>
                        {% menu_data_categories as menu %}
                        {% for collection in menu.collections %}
                        <a class="dropdown-item" href={{collection.get_absolute_url}}>{{collection.name|title}} </a>
                        {% endfor %}
                      </li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </ul>
        <div class="text-end">
          <a type="button" type="button" href="{% url "basket:basket_summary" %}" class="btn btn-warning btn-order">
            
            {% with total_qty=basket|length %}
            <div id="basket-qty" class="d-inline-flex">  
              {% if total_qty > 0 %}
                {{total_qty}}
              {% else %}
                0
              {% endif %}
            </div>    
            {% endwith %}
            
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-basket"
              viewBox="0 0 16 16">
              <path
                d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1v4.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 13.5V9a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h1.217L5.07 1.243a.5.5 0 0 1 .686-.172zM2 9v4.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V9H2zM1 7v1h14V7H1zm3 3a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 4 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 6 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3A.5.5 0 0 1 8 10zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5zm2 0a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 1 .5-.5z" />
            </svg>
            Basket
          </a>
          <button type="button" class="btn btn-outline-light me-2">Login</button>
          {% comment %} <button type="button" class="btn btn-warning">Sign-up</button> {% endcomment %}
        </div>
      </div>
    </div>
  </header>
  <div id="content">{% block content %} {% endblock %}</div>
</body>

</html>

templates/jewelry_store/home.html
{% extends './base.html' %}

{%load static %}
{%block title %} JewelryStore{% endblock %}



{%block content %}

{% load menu_data_products %}
{% load menu_data_categories %}

    <main>

        <section class="py-5 text-center container">
          <div class="row py-lg-1">
            <div class="col-lg-6 col-md-8 mx-auto">
              <h1 class="h1 fw-bold">Search, Read, Buy, Review</h1>
              <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator,
                etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
              <p>
                <a href="#" class="btn btn-primary my-2">Make an account</a>
              </p>
            </div>
          </div>
        </section>
      
        <div class="album py-5 bg-light">
          <div class="container">
      
            <div class="pb-3 h5">All Products</div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-6 g-3">
      
              {% for product in products %} 
              {% comment %} |slice:":3" {% endcomment %}
      
              <div class="col">
                <div class="card shadow-sm">
                  <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
                  <div class="card-body">
                    <p class="card-text">
                      <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.name}}</a>
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                      <small class="text-muted">material : {{product.material}}</small>
                    </div>
                    <div class="d-flex justify-content-between align-items-center">
                      <small class="text-muted">purity : 0{{product.purity}} </small>
                    </div>
                    <div class="d-flex justify-content-between align-items-center">
                      <small class="text-muted">weight : {{product.weight}}</small>
                    </div>
                    <div class="d-flex justify-content-between align-items-center">
                      <small class="text-muted">
                        <h5>price : {{product.price}}</h5>
                      </small>
                    </div>
                  </div>
                </div>
              </div>
      
              {% endfor %}
      
              {% for collection in collections %}
      
              <div class="col">
                <div class="card shadow-sm">
                  <img class="img-fluid" alt="Responsive image" src="{{ collection.image.url }}">
                  <div class="card-body">
                    <p class="card-text">
                      <a class="text-dark text-decoration-none" href="{{ collection.get_absolute_url }}">{{ collection.name }}</a>
                      <div>{{ collection.price }} PLN</div>
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                      <small class="text-muted">9min read</small>
                    </div>
                  </div>
                </div>
              </div>
              
              dupa {{prodo}}
              {% endfor %}

            </div>
          </div>
        </div>
        {% for c in collections%}
        <div>{{c}}</div>
        {% for p in products%}
        {%if c.id == p.colection_name_id %}
        
        {{prodo}}
        dupa {{c.prodo}}
        
        {{p.name}}{{p.price}}{{p.prodo}}DUPA{{object_list}}dupa2{{p.sum_total}}dupa3{{p.sum_total}}
        {%endif%} 
        <div></div>
        {%endfor%}
      {%endfor%}
      
        
        
      </main>



    
{% endblock %}