basket/urls.py
from re import template
from django.urls import path
from basket import views

app_name = 'basket'

urlpatterns = [
    path('', views.BasketSummary.as_view(), name='basket_summary'), 
    path('add/', views.BasketAddView.as_view(), name='basket_add'),
]
 

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jewelry_store.urls', namespace='jewelry_store')),
    path('basket/', include('basket.urls', namespace='basket')), 
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

jewelry_store/urls.py
from unicodedata import name

from django.urls import path

from jewelry_store.models import Category

from . import views

app_name = 'jewelry_store'

urlpatterns = [
    path('', views.AllListView.as_view(), name='all_products'),
    path('<slug:slug>', views.ProductView.as_view(), name='product_detail'),
    path('category/<slug:slug>/', views.CategoryView.as_view(), name='all_categories'),
    path('collection/<slug:slug>/', views.CollectionView.as_view(), name='all_collections'),
    
]
 

jewelry_store/models.py
from __future__ import annotations

import collections
from ast import arg, mod
from asyncio.windows_events import NULL
from decimal import Decimal
from email.policy import default
from itertools import product
from pickle import EMPTY_DICT, TRUE
from queue import Empty
from random import choice, choices
from tabnanny import verbose
from traceback import print_exception
from unicodedata import category, name

import pkg_resources
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Avg, Sum
from django.forms import DecimalField
from django.urls import reverse
from multiselectfield import MultiSelectField

Au = "gold"
Ag = "silver"
AuWoo = "wood&gold"
AgWoo = "wood&silver"
MATERIAL_CHOICES = [
    (Au, "gold"),
    (Ag,"silver"),
    (AuWoo, "wood&gold"),
    (AgWoo, "wood&silver"),
]

_999 = ".999"
_925 = ".925"
_875 = ".875"
_830 = ".830"
_800 = ".800"
_960 = ".960"
_750 = ".750"
_585 = ".585"
_500 = ".500"
_375 = ".375"
_333 = ".333"
PURITY_CHOICES =[
    (_999, ".999"),(_925, ".925"),(_875, ".875"),(_830, ".830"),
    (_800, ".800"),(_960, ".960"),(_750, ".750"),(_585, ".585"),
    (_500, ".500"),(_375, ".375"),(_333, ".333"),
]
_5  = "5/ø14mm/US4"
_6  = "6/ø14.3mm/US4+"
_7  = "7/ø14.6mm/"
_8  = "8/ø15mm/US5"
_9  = "9/ø15.3mm"
_10 = "10/ø15.6mm/US6-"
_11 = "11/ø16mm/US6"
_12 = "12/ø16.3mm"
_13 = "13/ø16.6mm"
_14 = "14/ø17mm/US7"
_15 = "15/ø17.3mm"
_16 = "16/ø17.6mm/US7+"
_17 = "17/ø18mm/US8"
_18 = "18/ø18.3mm"
_19 = "19/ø18.6mm/US9"
_20 = "20/ø19mm"
_21 = "21/ø19.3mm/US9+"
_22 = "22/ø19.6mm/US10"
_23 = "23/ø20mm"
_24 = "24/ø20.3mm/US11-"
_25 = "25/ø20.6mm/US11"
_26 = "26/ø21mm"
_27 = "27/ø21.3/US12"
_28 = "28/ø21.6"
_29 = "29/ø22mm/US13-"
_30 = "30/ø22.3mm/US13"
_31 = "31/ø22.6mm"
_32 = "32/ø23mm/US14"
_33 = "33/ø23.3mm"
_34 = "34/ø23.6mm"
SIZE_CHOICES  =  [
    (_5 , "5/ø14mm/US4"), (_6 , "6/ø14.3mm/US4+"), (_7 , "7/ø14.6mm/"),
    (_8 , "8/ø15mm/US5"),(_9 , "9/ø15.3mm"), (_10, "10/ø15.6mm/US6-"),
    (_11, "11/ø16mm/US6"), (_12, "12/ø16.3mm"), (_13, "13/ø16.6mm"),
    (_14, "14/ø17mm/US7"), (_15, "15/ø17.3mm"), (_16, "16/ø17.6mm/US7+"),
    (_17, "17/ø18mm/US8"), (_18, "18/ø18.3mm"), (_19, "19/ø18.6mm/US9"),
    (_20, "20/ø19mm"), (_21, "21/ø19.3mm/US9+"), (_22, "22/ø19.6mm/US10"),
    (_23, "23/ø20mm"), (_24, "24/ø20.3mm/US11-"), (_25, "25/ø20.6mm/US11"),
    (_26, "26/ø21mm"), (_27, "27/ø21.3/US12"), (_28, "28/ø21.6"),
    (_29, "29/ø22mm/US13-"), (_30, "30/ø22.3mm/US13"), (_31, "31/ø22.6mm"),
    (_32, "32/ø23mm/US14"), (_33, "33/ø23.3mm"), (_34, "34/ø23.6mm"),
 ]
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True,in_stock=True)

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse("jewelry_store:all_categories", args=[self.slug])
    
    def __str__(self):
        return self.name


class Collection(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)

    class Meta:
        verbose_name_plural = 'Collections'
    
    def get_absolute_url(self):
        return reverse("jewelry_store:all_collections", args=[self.slug])

    def __str__(self):
        return self.name

    @property
    def price(self):
        price = 0
        for product in self.products.all():
            price += product.price
        return price    


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    colection_name = models.ForeignKey(Collection, related_name='products', on_delete=models.CASCADE, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)   
    name = models.CharField(max_length=255)
    model_number = models.CharField(max_length=50)
    material = models.CharField(max_length=50, choices=MATERIAL_CHOICES, default="silver")
    purity = models.CharField(max_length=4, choices=PURITY_CHOICES,default=".925")
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    dimension = models.CharField(max_length=255)  ###!!!
    image = models.ImageField(upload_to = 'images/', default='images/default.jpg') ###!!! only one option
    price = models.DecimalField(max_digits=6, decimal_places=2)
    promo_price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    slug = models.SlugField(max_length=255)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    not_new = models.BooleanField(default=True)
    size = MultiSelectField(choices=SIZE_CHOICES,blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    products = ProductManager()

    @property
    def quantity(self):
        quantity = 0
        if not self.size:
            quantity = 1
        else:
            store = len(self.size)
            quantity += store
        return quantity



    class Meta():
        verbose_name_plural = 'Products'
        ordering = ('-created','-updated','weight', 'price',) 

    def get_absolute_url(self):
        return reverse("jewelry_store:product_detail", args=[self.slug])
    #def collection_sumarum(self):#    v=Product.objects.filter(price=True).aggregate(Sum('price'))#    print(v)# collections=Product.objects.get(pk=colection_name_id).aggregate(Sum('price'))# key_collections = Collection.id.#collections = Product.objects.filter(colection_name_id=1)#print('COLLECTIONS',collections)# for product in collections:#     Decimal(product.price)#     price = []#     a=type(Decimal(product.price))#     # print(a)#     # print(price)#     price.append(Decimal(product.price))# print(price)# print('FIRST',product.price)# print("ŁołołO",price)# v=Product.objects.aggregate(Sum('price')){{ p.collection_sumarum }}# print(collections)# return print('COLLECTIONS',collections)

    # def sum_total(self) :
    #     queryset = Product.objects.filter(in_stock=True)
    #     collections = Collection.objects.all()
    #     sum_tot=0
    #     for col in collections:
    #         for qs in queryset:
    #             if qs.colection_name_id == col.id:
    #                 sum_tot += qs.price
    #                 print('sum_tot',sum_tot)
    #     # queryset = sum_tot
    #     # print("bbbbbb",queryset)    
    #     return sum_tot

    def sum_total(self) :
        queryset = Product.objects.filter(in_stock=True)
        collections = Collection.objects.all()
        sum_tot=0
        for col in collections:
            for qs in queryset:
                if qs.colection_name_id == col.id:
                    sum_tot += qs.price
                    print('sum_tot',sum_tot)
        # queryset = sum_tot
        # print("bbbbbb",queryset)    
    def sum_total(self) :
        queryset = Product.products.filter(in_stock=True)
        collections = Collection.objects.all()
        sum_tot=0
        sum_tot_list = []
        num = len(collections)
        print('numer dlugosci listy',num)
        for col in collections:
            print(col.id)
            print(collections)    
                
            
            for qs in queryset:
                # for col.id in collections:
                    # print("col.id", col.id)
                if col.id ==  qs.colection_name_id:
                   
                    sum_tot += qs.price
                    
                    
                    print('sum_tot',sum_tot)
                    sum_tot_list.append(sum_tot)
        # queryset = sum_tot
        # print("bbbbbb",queryset)    
            return sum_tot

    def __str__(self):
        return self.name


# python manage.py makemigrations and python manage.py migrate

        

jewelry_store/views.py
import collections
from gettext import Catalog
from multiprocessing import context

from django.db.models import Sum
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.views.generic import DetailView, ListView
from pyexpat import model

import jewelry_store

from .models import Category, Collection, Product


class AllListView(ListView):
    context_object_name = 'all_products'
    queryset = Product.products.filter(in_stock=True, is_active = True)
    template_name = 'jewelry_store/home.html'
    # pk_url_kwarg='collection_id' 
    
    def get_context_data(self, **kwargs,):
        
        context = super(AllListView,self).get_context_data(**kwargs)
           
        print('dupaaaa',kwargs)
        # print(context)
        context['collections'] =  Collection.objects.all
        context['products'] = self.queryset
        
        context['sum']= Product.products.all()
        
        print("DUPA1",Product.products.filter(colection_name=1))
        print("DUPA2",Product.products.filter(colection_name=self.kwargs.get('collection_id')))
        context['prodo'] = Product.products.all().aggregate(Sum('price'))['price__sum']
        print("context['prodo']",context['prodo'])

        return context
        
    def get_queryset(self) :
        queryset = Product.products.filter(in_stock=True, is_active=True)
        collections = Collection.objects.all()
        sum_tot=0
        for col in collections:
            for qs in queryset:
                if qs.colection_name_id == col.id:
                    sum_tot += qs.price
                    print('sum_tot',sum_tot)
        queryset = sum_tot
        print("aaaaaa",queryset)    
        return queryset


class ProductView(DetailView):
    context_object_name = 'product_detail'
    model = Product
    template_name = "jewelry_store/product/detail_product.html"

    # it shows 404 when object is not in stock 
    def get_object(self):
        obj = super().get_object()
        obj = get_object_or_404(Product, slug=self.kwargs['slug'] ,in_stock=True)
        return obj
class CategoryView(ListView):
    model = Category
    context_object_name = 'all_categories'
    template_name = 'jewelry_store/product/category.html'

    def get_queryset(self):
        products = Product.products.filter(category__slug=self.kwargs['slug'],in_stock=True, is_active=True)
        # the same but shorter, was down # category = get_object_or_404(Category,slug=self.kwargs['slug'])# print(category)# products = Product.objects.filter(category=category)# print(products)
        return products    #Product.objects.filter(category=category)#products#Product.objects.filter(category=category)#products#
    
    def get_context_data(self,**kwargs):
        context = super(CategoryView,self).get_context_data(**kwargs)
        context['category'] = get_object_or_404(Category,slug=self.kwargs['slug'])
        return context
class CollectionView(ListView):
    #  context_object_name = 'collection_detail'#  queryset = Product.objects.all#  template_name = "jewelry_store/product/detail_collection.html"#  def get_context_data(self,**kwargs):#     context = super(ListView,self).get_context_data(**kwargs)#     context['collections'] =  Collection.objects.all #     context['products'] = self.queryset#     return context
    model = Collection
    context_object_name = 'all_collections'
    template_name = 'jewelry_store/product/collections.html'
    pk_url_kwarg = 'collection_id'
    
    def get_queryset(self):
        products = Product.products.filter(colection_name__slug=self.kwargs['slug'],in_stock=True, is_active=True)
        # the same but shorter, was down # category = get_object_or_404(Category,slug=self.kwargs['slug'])# print(category)# products = Product.objects.filter(category=category)# print(products)
        return products    #Product.objects.filter(category=category)#products#Product.objects.filter(category=category)#products#
    
    def get_context_data(self,**kwargs):
        context = super(CollectionView,self).get_context_data(**kwargs)
        context['collection'] = get_object_or_404(Collection,slug=self.kwargs['slug'])
        products = Product.products.filter(colection_name__slug=self.kwargs['slug'])
        context['prodo'] = products.aggregate(Sum('price'))
        return context

templates/jewelry_store/product/category.html
{% extends '../base.html' %}

{%load static %}
{%block title %} {{category.name}} {%endblock %}



{%block content %}

{% load menu_data_products %}
{% load menu_data_categories %}

 


    <main>
        <div class="album py-5 bg-light">
          <div class="container">
            <div class="pb-3 h5">{{category.name}}'s</div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
            
                {% for product in object_list %} 
                {% comment %} |slice:":3" {% endcomment %}
                
                <div class="col">
                  <div class="card shadow-sm">
                    <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
                    <div class="card-body">
                      <p class="card-text">
                        <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.name}}</a>
                      </p>
                      <div class="d-flex justify-content-between align-items-center">
                        <small class="text-muted">material : {{product.material}}</small>
                      </div>
                      <div class="d-flex justify-content-between align-items-center">
                        <small class="text-muted">purity : 0{{product.purity}} </small>
                      </div>
                      <div class="d-flex justify-content-between align-items-center">
                        <small class="text-muted">weight : {{product.weight}}</small>
                      </div>
                      <div class="d-flex justify-content-between align-items-center">
                        <small class="text-muted">
                          <h5>price : {{product.price}}</h5>
                        </small>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
      
              {% for collection in collections %}
      
              <div class="col">
                <div class="card shadow-sm">
                  <img class="img-fluid" alt="Responsive image" src="{{ collection.image.url }}">
                  <div class="card-body">
                    <p class="card-text">
                      <a class="text-dark text-decoration-none" href="{{ collection.get_absolute_url }}">{{ collection.name }}</a>
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                      <small class="text-muted">9min read</small>
                    </div>
                  </div>
                </div>
              </div>
      
              {% endfor %}

            </div>
          </div>
        </div>
      
      
      </main>



    
{% endblock %}

templates/jewelry_store/product/collections.html
{% extends '../base.html' %}

{%load static %}

{%block title %}
{{collection.name}}
{% endblock %}


{%block content %}

{% load menu_data_products %}
{% load menu_data_categories %}


    <main>
        <div class="album py-5 bg-light">
          <div class="container">
            <div class="pb-3 h5">{{collection.name}}</div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
            
                {% for product in object_list %} 
                {% comment %} |slice:":3" {% endcomment %}
                
                <div class="col">
                  <div class="card shadow-sm">
                    <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
                    <div class="card-body">
                      <p class="card-text">
                        <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.name}}</a>
                      </p>
                      <div class="d-flex justify-content-between align-items-center">
                        <small class="text-muted">material : {{product.material}}</small>
                      </div>
                      <div class="d-flex justify-content-between align-items-center">
                        <small class="text-muted">purity : 0{{product.purity}} </small>
                      </div>
                      <div class="d-flex justify-content-between align-items-center">
                        <small class="text-muted">weight : {{product.weight}}</small>
                      </div>
                      <div class="d-flex justify-content-between align-items-center">
                        <small class="text-muted">
                          {% comment %}  {% endcomment %}
                        </small>
                      </div>
                    </div>
                  </div>
                </div>
                
                {% endfor %}
                
            </div>
            {{prodo.price__sum}}
            
            
            
            
            
            {% comment %} {%if %} {% endcomment %}
            
          </div>
        </div>
      
      
      </main>



    
{% endblock %}

















{% comment %} {%block content %}

<div>
    dupa
    
    <div>dupa 1{{collection_detail}}</div>
        <div>dupa 2{{products}}</div>
            <div>dupa 3{{collections}}</div>
                <div>dupa 4{{Product.collection_name}}</div>
    
{% comment %} {{products}} {% endcomment %}
{% comment %} {% for p in object_list%}
{% comment %} {{p.colection_name}}{{p.name}} {% endcomment %}
{% comment %} {%if p.colection_name %}
{{p.colection_name}}{{p.name}}{{p.material}}


<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ p.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ p.name }}</h1>
                <p> (Model number)  <span class="lead">{{ p.model_number }}</span> </p>
                <p>material : {{ p.material}}, purity : 0{{ p.purity}}, </p>
                <p>weight : {{ p.weight}} grams</p>
                <p>dimension : {{ p.dimension}} </p>
                <p>size : {{ p.size}} grams</p>

                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6 h5">Price</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">PLN {{ p.collection_sumarum }}{{p.price}}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                
                                
                                <label for="select">Size</label>
                                <select id="select">
                                    {% comment %} patern version {% endcomment %}
                                    
                                    {% comment %} {% for size in p.size%}
                                    {%if size %}  
                                    <option value="">{{ size }}</option>
                                    {%endif%}
                                    {% endfor %}
                                    
                                    
                                    {% comment %} {% if product_detail.size%}
                                    <div>{{size}}</div>   
                                    <option value="">{{ product_detail.size }}</option>
                                    {% endif %}  {% endcomment %}
                                    {% comment %} </select>

                            </div>
                            <div class="col-6 text-end"><button type="button" class="btn btn-secondary btn-sm">Add to
                                    basket</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main> {% endcomment %}

{% comment %} </div>  {% endcomment %} 
{% comment %}  
{%endif%}

{% endfor %} {% endcomment %}


{% comment %} {{collections}} {% endcomment %}
{% comment %} </div> {% endcomment %}



{% comment %} {% endblock %} {% endcomment %}

templates/jewelry_store/product/detail_product.html
{% extends '../base.html' %}

{%load static %}

{%block title %}
{{product_detail.name}}
{% endblock %}

{%block content %}


{% comment %} {{object.name}} without context_object_name in views {% endcomment %}

<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image"
                    src="{{ product_detail.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product_detail.name }}</h1>
                <p> (Model number) <span class="lead">{{ product_detail.model_number }}</span> </p>
                <p>material : {{ product_detail.material}}, purity : 0{{ product_detail.purity}}, </p>
                <p>weight : {{ product_detail.weight}} grams</p>
                <p>dimension : {{ product_detail.dimension}} </p>
                <p>size : {{ product_detail.size}} grams</p>

                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6 h5">Price</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">PLN {{ product_detail.price }}</span>
                            </div>
                        </div>
                        <div class="row p-3">
                            <div class="col-6 h8">QTY</div>
                            <div name== "basket-qty" class="col-6 text-end" id = "basket-qty" value= "{{ product_detail.quantity }}"><span class="h8 fw-bold">{{ product_detail.quantity }} </span>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">


                                <label for="select">Size</label>
                                <select id="select">
                                    {% comment %} patern version {% endcomment %}
                                    {% for size in product_detail.size%}
                                    <option value="">{{ size }}</option>
                                    {% endfor %}


                                    {% comment %} {% if product_detail.size%}
                                    <div>{{size}}</div>
                                    <option value="">{{ product_detail.size }}</option>
                                    {% endif %} {% endcomment %}
                                </select>
                                <div>

                                </div>
                            </div>
                                <div class="col-6 text-end">
                                    <button type="button" id="add-button" value={{product_detail.id}} class="btn btn-secondary btn-sm">Add to basket</button>
                                
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>

<script>
    $(document).on('click', '#add-button', function (e) {
                // prevent action specyfic for element
        e.preventDefault();
        //console.log($('#select option:selected').text())
        
                //setup ajax request 
        $.ajax({
                //send data to the server
            type: 'POST',
                //where we gona send this data
            url: '{% url "basket:basket_add" %}',
                //finaly data
            data: {
                productid: $('#add-button').val(),//product_detailid: $('#add-button').val(),
                productsize: $('#select option:selected').text(),
                productqty: "{{product_detail.quantity}}",//document.getElementById('basket-qty'),
                //security reason
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            // if succes
            success: function(json){
            //console.log(json)
            document.getElementById("basket-qty").innerHTML = json.qty
            console.log(json)
            },
            error: function (xhr, errmsg, err) {}        

        });

    })

</script>



{% endblock %}